# Use the official Apache Airflow image as the base image
FROM apache/airflow:2.5.3

# Copy the requirements.txt file to the container
COPY requirements.txt /tmp/requirements.txt

# Install Python packages from the requirements.txt file
RUN pip install --no-cache-dir -r /tmp/requirements.txt