FROM mongo:latest

RUN apt-get update && \
    apt-get install -y wget && \
    wget -qO - https://www.mongodb.org/static/pgp/server-4.4.asc | apt-key add - && \
    echo "deb http://repo.mongodb.org/apt/debian buster/mongodb-org/4.4 main" | tee /etc/apt/sources.list.d/mongodb-org-4.4.list && \
    apt-get update && \
    apt-get install -y mongodb-org-shell && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*