version: "3.9"
services:
  mongodb:
    build:
      context: .
      dockerfile: Dockerfile.mongodb
    container_name: mongodb
    command: mongod --auth
    env_file:
      - .env
    volumes:
      - mongodb_data:/data/db
      - ./mongo-init:/docker-entrypoint-initdb.d
    ports:
      - "27017:27017"

  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  airflow:
    image: apache/airflow:2.2.4
    container_name: airflow
    depends_on:
      - mongodb
      - postgres
    env_file:
      - .env
    environment:
      - LOAD_EX=n
    entrypoint: /bin/bash -c "/opt/airflow/scripts/entrypoint.sh || true && airflow webserver"
    volumes:
      - ./dags:/opt/airflow/dags
      - ./scripts:/opt/airflow/scripts
    ports:
      - "8080:8080"

  jupyter-pyspark:
    image: jupyter/pyspark-notebook:latest
    container_name: jupyter-pyspark
    depends_on:
      - mongodb
    ports:
      - "8888:8888"
    volumes:
      - ./notebooks:/home/jovyan/work
      - ./data:/home/jovyan/data

volumes:
  mongodb_data:
  postgres_data: